export enum ErrorsEnum {
	TOKEN_EXPRIED = "TOKEN_EXPRIED",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	WRONG_PASSWORD = "WRONG_PASSWORD",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	DUPLICATE_USERNAME = "DUPLICATE_USERNAME",
	DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE",
}
